# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gbcback/anki/proto/anki.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gbcback/anki/proto/anki.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgbcback/anki/proto/anki.proto\x12\x04\x61nki\";\n\nMediaEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x11\n\tsha1_hash\x18\x03 \x01(\x0c\"1\n\x0cMediaEntries\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.anki.MediaEntry\"\x1d\n\x0eNotetypeConfig\x12\x0b\n\x03\x63ss\x18\x03 \x01(\t\"J\n\x08Notetype\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\x06\x63onfig\x18\x07 \x01(\x0b\x32\x14.anki.NotetypeConfig\"4\n\x0eTemplateConfig\x12\x10\n\x08q_format\x18\x01 \x01(\t\x12\x10\n\x08\x61_format\x18\x02 \x01(\t\">\n\x08Template\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\x06\x63onfig\x18\x05 \x01(\x0b\x32\x14.anki.TemplateConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gbcback.anki.proto.anki_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIAENTRY']._serialized_start=39
  _globals['_MEDIAENTRY']._serialized_end=98
  _globals['_MEDIAENTRIES']._serialized_start=100
  _globals['_MEDIAENTRIES']._serialized_end=149
  _globals['_NOTETYPECONFIG']._serialized_start=151
  _globals['_NOTETYPECONFIG']._serialized_end=180
  _globals['_NOTETYPE']._serialized_start=182
  _globals['_NOTETYPE']._serialized_end=256
  _globals['_TEMPLATECONFIG']._serialized_start=258
  _globals['_TEMPLATECONFIG']._serialized_end=310
  _globals['_TEMPLATE']._serialized_start=312
  _globals['_TEMPLATE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
